apiVersion: v1
kind: PersistentVolume
metadata:
  name: dsocket-vol
  labels:
    type: dsocket-vol
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany      
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsocket-vol-claim
spec:
  selector:
    matchLabels: 
      type: dsocket-vol
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dlib-vol-claim
spec:
  selector:
    matchLabels: 
      type: dsocket-vol
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
